package config

const (
	POSTGRES_USER    string = "POSTGRES_USER"
	POSTGRES_PASS    string = "POSTGRES_PASS"
	POSTGRES_HOST    string = "POSTGRES_HOST"
	POSTGRES_DBNAME  string = "POSTGRES_DBNAME"
	POSTGRES_PORT    string = "POSTGRES_PORT"
	POSTGRES_SSLMODE string = "POSTGRES_SSLMODE"

	RABBITMQ_DEFAULT_USER string = "RABBITMQ_DEFAULT_USER"
	RABBITMQ_DEFAULT_PASS string = "RABBITMQ_DEFAULT_PASS"
	RABBITMQ_HOST         string = "RABBITMQ_HOST"
	RABBITMQ_PORT         string = "RABBITMQ_PORT"
	RABBITMQ_URL          string = "RABBITMQ_URL"
	CHAT_EXCHANGE         string = "CHAT_EXCHANGE"
	MEETING_EXCHANGE      string = "MEETING_EXCHANGE"

	APP_PORT string = "APP_PORT"
	APP_ENV  string = "APP_ENV"

	JWKS_URL string = "JWKS_URL"
)
