package config

const (
	REDIS_ADDR     string = "REDIS_ADDR"
	REDIS_PASSWORD string = "REDIS_PASSWORD"
	REDIS_DB       string = "REDIS_DB"

	RABBITMQ_DEFAULT_USER string = "RABBITMQ_DEFAULT_USER"
	RABBITMQ_DEFAULT_PASS string = "RABBITMQ_DEFAULT_PASS"
	RABBITMQ_HOST         string = "RABBITMQ_HOST"
	RABBITMQ_PORT         string = "RABBITMQ_PORT"
	RABBITMQ_URL          string = "RABBITMQ_URL"

	JWT_SECRET string = "JWT_SECRET"
	JWKS_URL   string = "JWKS_URL"

	APP_NAME string = "APP_NAME"
	APP_PORT string = "APP_PORT"
	APP_ENV  string = "APP_ENV"

	NOTIFICATION_EXCHANGE_QUEUE_NAME string = "NOTIFICATION_EXCHANGE_QUEUE_NAME"
	EVENT_EXCHANGE_QUEUE_NAME        string = "EVENT_EXCHANGE_QUEUE_NAME"
)
