// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/meeting/end": {
            "post": {
                "description": "Ends a meeting based on the provided DTO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ending meetings"
                ],
                "summary": "End a meeting",
                "parameters": [
                    {
                        "description": "End Meeting DTO",
                        "name": "meeting",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.EndMeetingDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/server.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.MeetingDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Ends a meeting based on the provided DTO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ending meetings"
                ],
                "summary": "End a meeting",
                "parameters": [
                    {
                        "description": "End Meeting DTO",
                        "name": "meeting",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.EndMeetingDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/server.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.MeetingDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/meeting/start": {
            "put": {
                "description": "Starts a meeting based on the provided DTO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "start meetings"
                ],
                "summary": "Start a meeting",
                "parameters": [
                    {
                        "description": "Start Meeting DTO",
                        "name": "meeting",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.StartMeetingDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Meeting details after operation",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/server.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.MeetingDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request due to invalid data or DTO type",
                        "schema": {
                            "$ref": "#/definitions/server.Response"
                        }
                    },
                    "405": {
                        "description": "Method not allowed (only POST supported)",
                        "schema": {
                            "$ref": "#/definitions/server.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Starts a meeting based on the provided DTO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "start meetings"
                ],
                "summary": "Start a meeting",
                "parameters": [
                    {
                        "description": "Start Meeting DTO",
                        "name": "meeting",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.StartMeetingDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Meeting details after operation",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/server.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.MeetingDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request due to invalid data or DTO type",
                        "schema": {
                            "$ref": "#/definitions/server.Response"
                        }
                    },
                    "405": {
                        "description": "Method not allowed (only POST supported)",
                        "schema": {
                            "$ref": "#/definitions/server.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/meeting/{class_id}": {
            "get": {
                "description": "Fetches information about active meeting for given class. \"members\" will be empty.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meetings class"
                ],
                "summary": "Gets active meeting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Class ID",
                        "name": "class_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Found active meeting",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/server.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.MeetingDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Empty class id",
                        "schema": {
                            "$ref": "#/definitions/server.Response"
                        }
                    },
                    "404": {
                        "description": "Not found or not started yet",
                        "schema": {
                            "$ref": "#/definitions/server.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.EndMeetingDTO": {
            "type": "object",
            "required": [
                "classId",
                "meetingID",
                "members"
            ],
            "properties": {
                "classId": {
                    "description": "Class id - where meeting will be started (UUIDv4)\nrequired: true",
                    "type": "string"
                },
                "meetingID": {
                    "description": "Meeting unique identifier (UUIDv4)\nrequired: true",
                    "type": "string"
                },
                "members": {
                    "description": "Members who participated in the meeting (minimum 2)\nrequired: true",
                    "type": "array",
                    "minItems": 2,
                    "items": {
                        "$ref": "#/definitions/dto.UserDTO"
                    }
                }
            }
        },
        "dto.MeetingDTO": {
            "type": "object",
            "properties": {
                "meetingId": {
                    "description": "Meeting unique identifier",
                    "type": "string"
                },
                "members": {
                    "description": "Members who participated in the meeting",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UserDTO"
                    }
                },
                "timestamp": {
                    "description": "Timestamp of started meeting",
                    "type": "integer"
                },
                "title": {
                    "description": "Meetings title",
                    "type": "string"
                }
            }
        },
        "dto.StartMeetingDTO": {
            "type": "object",
            "required": [
                "classId",
                "members",
                "title"
            ],
            "properties": {
                "classId": {
                    "description": "Class id - where meeting will be started (UUIDv4)\nrequired: true",
                    "type": "string"
                },
                "members": {
                    "description": "Members participating in the meeting (minimum 2)\nrequired: true",
                    "type": "array",
                    "minItems": 2,
                    "items": {
                        "$ref": "#/definitions/dto.UserDTO"
                    }
                },
                "title": {
                    "description": "The title of the class eg. C++ Object oriented: pointers\nreqiured: true",
                    "type": "string"
                }
            }
        },
        "dto.UserDTO": {
            "type": "object",
            "required": [
                "firstName",
                "id",
                "lastName"
            ],
            "properties": {
                "avatarURL": {
                    "description": "URL to the user's avatar image\nrequired: false",
                    "type": "string"
                },
                "firstName": {
                    "description": "User's first name\nrequired: true",
                    "type": "string",
                    "minLength": 2
                },
                "id": {
                    "description": "User unique identifier (UUIDv4)\nrequired: true",
                    "type": "string"
                },
                "lastName": {
                    "description": "User's last name\nrequired: true",
                    "type": "string",
                    "minLength": 2
                }
            }
        },
        "server.Response": {
            "description": "Standard API response format containing message, data, and success status",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data contains the response payload (optional)"
                },
                "message": {
                    "description": "Message contains the response message",
                    "type": "string"
                },
                "success": {
                    "description": "Success indicates whether the operation was successful",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8003",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Meeting Scheduler API",
	Description:      "Serivce to requesting meetings in .tutora",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
