basePath: /api/v1
definitions:
  dto.EndMeetingDTO:
    properties:
      meetingID:
        description: |-
          Meeting unique identifier (UUIDv4)
          required: true
        type: string
      members:
        description: |-
          Members who participated in the meeting (minimum 2)
          required: true
        items:
          $ref: '#/definitions/dto.UserDTO'
        minItems: 2
        type: array
    required:
    - meetingID
    - members
    type: object
  dto.StartMeetingDTO:
    properties:
      members:
        description: |-
          Members participating in the meeting (minimum 2)
          required: true
        items:
          $ref: '#/definitions/dto.UserDTO'
        minItems: 2
        type: array
    required:
    - members
    type: object
  dto.UserDTO:
    properties:
      avatarURL:
        description: |-
          URL to the user's avatar image
          required: false
        type: string
      firstName:
        description: |-
          User's first name
          required: true
        minLength: 2
        type: string
      id:
        description: |-
          User unique identifier (UUIDv4)
          required: true
        type: string
      lastName:
        description: |-
          User's last name
          required: true
        minLength: 2
        type: string
    required:
    - firstName
    - id
    - lastName
    type: object
  response.Response:
    description: Standard API response format containing message, data, and success
      status
    properties:
      data:
        description: Data contains the response payload (optional)
      message:
        description: Message contains the response message
        type: string
      success:
        description: Success indicates whether the operation was successful
        type: boolean
    type: object
host: default localhost:8080
info:
  contact: {}
  description: Serivce to requesting meetings in .tutora
  title: Meeting Scheduler API
  version: "1.0"
paths:
  /api/v1/meeting/end:
    post:
      consumes:
      - application/json
      description: Ends a meeting based on the provided DTO
      parameters:
      - description: End Meeting DTO
        in: body
        name: meeting
        required: true
        schema:
          $ref: '#/definitions/dto.EndMeetingDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Meeting details after operation
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad request due to invalid data or DTO type
          schema:
            $ref: '#/definitions/response.Response'
        "405":
          description: Method not allowed (only POST supported)
          schema:
            $ref: '#/definitions/response.Response'
      summary: End a meeting
      tags:
      - meetings
  /api/v1/meeting/start:
    post:
      consumes:
      - application/json
      description: Starts a meeting based on the provided DTO
      parameters:
      - description: Start Meeting DTO
        in: body
        name: meeting
        required: true
        schema:
          $ref: '#/definitions/dto.StartMeetingDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Meeting details after operation
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad request due to invalid data or DTO type
          schema:
            $ref: '#/definitions/response.Response'
        "405":
          description: Method not allowed (only POST supported)
          schema:
            $ref: '#/definitions/response.Response'
      summary: Start a meeting
      tags:
      - meetings
swagger: "2.0"
